basic: ../jokk/server.py ./basic/config.json
	python ../jokk/server.py -c ./basic/config.json -s
	python ../jokk/server.py -c ./basic/config.json

jsonp: ../jokk/server.py ./jsonp/config.json
	python ../jokk/server.py -c ./jsonp/config.json

status: ../jokk/server.py ./status/config.json
	python ../jokk/server.py -c ./status/config.json

.PHONY: basic jsonp status
